/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.41.0.0
 *
 * Project: 'ex5' 
 * Target:  'Target_1' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "LPC407x_8x_177x_8x.h"



#endif /* RTE_COMPONENTS_H */
